# GitHub Pages Configuration
theme: null
plugins: []
include:
  - assets/
  - js/
  - css/
  - _*
exclude:
  - node_modules/
  - src/
  - package.json
  - package-lock.json
  - vite.config.js
  - vite.config.js.bak
  - firebase.json
  - firestore.rules
  - storage.rules
  - .env
  - .env.local
  - .firebaserc
  - README.md
  - .gitignore
  - public/
  - public-backup/
  - dist/
  - dist-unused/